services:
  #
  # Mail Servers
  #

  # Valid: MTA-STS with Let's Encrypt
  postfix-le-mta-sts:
    build:
      context: postfix
      args:
        name: a
        certdomain: audit.alexsci.com
    restart: unless-stopped
    networks:
      privatenet:
    ports:
      - "${IP0:?error}:${HOST_MAIL_PORT:?error}:25"
    volumes:
      - "${CERTS_PATH:?error}/:/etc/letsencrypt/:ro"

  # Invalid: MTA-STS with unknown/untrusted CA
  postfix-uk-mta-sts:
    build:
      context: postfix
      args:
        name: b
        certdomain: mail-b.audit.alexsci.com
    restart: unless-stopped
    networks:
      privatenet:
    ports:
      - "${IP1:?error}:${HOST_MAIL_PORT:?error}:25"
    volumes:
      - "${INVALID_CERTS_PATH:?error}/:/etc/letsencrypt/:ro"

  # Value but insecure: Unknown/untrusted CA (no MTA-STS)
  postfix-uk:
    build:
      context: postfix
      args:
        name: c
        certdomain: mail-c.audit.alexsci.com
    restart: unless-stopped
    networks:
      privatenet:
    ports:
      - "${IP2:?error}:${HOST_MAIL_PORT:?error}:25"
    volumes:
      - "${INVALID_CERTS_PATH:?error}/:/etc/letsencrypt/:ro"

  # Invalid: MTA-STS with unknown/untrusted CA
  # but with a spoofed (non-DNSSEC) DANE record
  postfix-uk-mta-sts-dane:
    build:
      context: postfix
      args:
        name: d
        certdomain: mail-d.audit.alexsci.com
    restart: unless-stopped
    networks:
      privatenet:
    ports:
      - "${IP3:?error}:${HOST_MAIL_PORT:?error}:25"
    volumes:
      - "${INVALID_CERTS_PATH:?error}/:/etc/letsencrypt/:ro"

  #
  # API for web frontend
  #
  api:
    build: api 
    restart: unless-stopped
    networks:
      privatenet:
        ipv4_address: 10.11.26.34
    depends_on:
      - valkey

  #
  # Static hosting for MTA-STS policy files
  #
  nginx:
    build:
      context: nginx
      args:
        certdomain: audit.alexsci.com
    restart: unless-stopped
    networks:
      privatenet:
    ports:
      - "${IP0:?error}:${HOST_WEBSECURE_PORT:?error}:443"
    volumes:
      - "${CERTS_PATH:?error}/:/etc/letsencrypt/:ro"
    depends_on:
      - api

  #
  # Database
  #
  valkey:
    image: "valkey/valkey:7.2-alpine3.20"
    networks:
      privatenet:

networks:
  privatenet:
    name: postfix-audit-net
    external: false
    internal: false
    ipam:
      driver: default
      config:
        - subnet: 10.11.26.0/24
          ip_range: 10.11.26.0/26
          gateway: 10.11.26.254

